version: "3.9"
services:
  linkmint:
    build: .
    image: linkmint/app:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 5s
      retries: 5
